default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  host:     <%= ENV.fetch("DB_HOST", "127.0.0.1") %>
  port:     <%= ENV.fetch("DB_PORT", 5432) %>
  username: <%= ENV.fetch("DB_USER", "postgres") %>
  password: <%= ENV.fetch("DB_PASSWORD", "postgres") %>

development:
  <<: *default
  database: <%= ENV.fetch("DB_NAME", "rig_radar_development") %>

test:
  <<: *default
  database: <%= ENV.fetch("DB_TEST_NAME", "rig_radar_test") %>

# Production stays on DATABASE_URL (e.g. Render)
production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
