name: "Ruby on Rails CI"

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4
      - run: bundle install --jobs 4 --retry 3
      - run: bundle exec rubocop --format simple

  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4

      # Install gems
      - name: Install dependencies
        run: bundle install --jobs 4 --retry 3

      # Ensure we have a database.yml (if you don't commit one)
      - name: Create database.yml
        run: |
          cat > config/database.yml <<'EOF'
          test:
            adapter: postgresql
            encoding: unicode
            database: rig_radar_test
            host: localhost
            username: postgres
            password: postgres
          EOF

      # Create & load schema
      - name: Setup test database
        run: |
          bundle exec rails db:create db:schema:load

      # Run your test suite
      - name: Run specs
        run: bundle exec rspec
