name: Ruby on Rails CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: rails_test
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password
        ports: ["5432:5432"]
        options: >-
          --health-cmd "pg_isready -U rails"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      RAILS_ENV: test
      DATABASE_URL: postgres://rails:password@localhost:5432/rails_test

    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4'
          bundler-cache: true

      - name: Prepare DB
        run: bin/rails db:prepare

      - name: Run tests (RSpec if present)
        if: ${{ hashFiles('spec/**/*') != '' }}
        run: bundle exec rspec

      - name: Run tests (Minitest if present)
        if: ${{ hashFiles('test/**/*') != '' }}
        run: bin/rails test

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4'
          bundler-cache: true

      - name: RuboCop
        run: bundle exec rubocop --parallel

      # --- JS lint (only if package.json exists) ---
      - name: Setup Node
        if: ${{ hashFiles('package.json') != '' }}
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install npm deps
        if: ${{ hashFiles('package.json') != '' }}
        run: npm ci

      - name: Run npm lint (only if script exists)
        if: ${{ hashFiles('package.json') != '' }}
        run: |
          if jq -e '.scripts.lint' package.json > /dev/null 2>&1; then
            npm run lint
          else
            echo "No npm lint script; skipping."
          fi
